# pull base image
FROM dockerfile/ubuntu

# suppress apt-get warning
ENV DEBIAN_FRONTEND noninteractive

# install Java
RUN \
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/cache/oracle-jdk8-installer

# install Bitcoin Core dependencies
RUN add-apt-repository ppa:bitcoin/bitcoin \
 && apt-get update \
 && apt-get install -y --no-install-recommends bitcoin-qt

# (Demo) install vnc, xvfb, openbox xterm
RUN add-apt-repository 'deb http://dl.google.com/linux/chrome/deb/ stable main' \
 && add-apt-repository 'deb http://mirrors.kernel.org/ubuntu trusty main' \
 && apt-get update \
 && apt-get install -y --no-install-recommends x11vnc xvfb openbox xterm menu \
 && mkdir ~/.vnc \
# -----------------------------------------
# Change the VNC remote access password
 && x11vnc -storepasswd 1234 ~/.vnc/passwd
# -----------------------------------------

# clean up
RUN  apt-get clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# define working directory
WORKDIR /aicoin

# user
RUN groupadd -r aicoin -g 433 && \
useradd -u 431 -r -g aicoin -d /work -s /sbin/nologin -c "aicoin user" aicoin && \
chown -R aicoin:aicoin /aicoin

# demo machine UUID for D-Bus
RUN echo "8d4b197c687db9c72d5a3bcb547de54f" > /etc/machine-id

# variables
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
ENV REPOSITORIES ../repositories
ENV SECURITY_DIR /aicoin
ENV TIMEZONE America/Chicago
ENV LISTENING_PORT 5048

# -----------------------------------------
# change to unique values of your choosing
ENV CONTAINER Bob
ENV RPC_USER rpctestuser
ENV RPC_PASSWORD rpctestpassword
# -----------------------------------------

# Demo aicoind port
EXPOSE 8333
# A.I. Coin port
EXPOSE 5048
# VNC port
EXPOSE 5900
# Java remote debugger port
EXPOSE 10000

# define default command
CMD ["bash"]
