/* Generated By:JavaCC: Do not edit this line. TurtleStatementParserConstants.java */
package org.texai.turtleStatementParser;

public interface TurtleStatementParserConstants {

  int EOF = 0;
  int LPAREN = 8;
  int RPAREN = 9;
  int LBRACE = 10;
  int RBRACE = 11;
  int LBRACKET = 12;
  int RBRACKET = 13;
  int SEMICOLON = 14;
  int COMMA = 15;
  int COLON = 16;
  int QUESTION = 17;
  int DASH = 18;
  int IN = 19;
  int INT_SCHEMA = 20;
  int LONG_SCHEMA = 21;
  int DOUBLE_SCHEMA = 22;
  int INTEGER_LITERAL = 23;
  int DECIMAL_LITERAL = 24;
  int HEX_LITERAL = 25;
  int OCTAL_LITERAL = 26;
  int FLOATING_POINT_LITERAL = 27;
  int EXPONENT = 28;
  int CHARACTER_LITERAL = 29;
  int STRING_LITERAL = 30;
  int DOT = 31;
  int LETTER_OR_QUESTION_MARK = 32;
  int IDENTIFIER = 33;
  int LETTER = 34;
  int DIGIT = 35;
  int VARIABLE = 36;
  int QNAME = 37;
  int URI_GENERAL_DELIMITER = 38;
  int URI_SUB_DELIMITER = 39;
  int URI_RESERVED_CHAR = 40;
  int URI_UNRESERVED_CHAR = 41;
  int LANGLE = 42;
  int RANGLE = 43;
  int URI = 44;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\":\"",
    "\"?\"",
    "\"-\"",
    "\"in\"",
    "\"^^<http://www.w3.org/2001/XMLSchema#int>\"",
    "\"^^<http://www.w3.org/2001/XMLSchema#long>\"",
    "\"^^<http://www.w3.org/2001/XMLSchema#double>\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\".\"",
    "<LETTER_OR_QUESTION_MARK>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<VARIABLE>",
    "<QNAME>",
    "<URI_GENERAL_DELIMITER>",
    "<URI_SUB_DELIMITER>",
    "<URI_RESERVED_CHAR>",
    "<URI_UNRESERVED_CHAR>",
    "\"<\"",
    "\">\"",
    "<URI>",
  };

}
