/* Generated By:JavaCC: Do not edit this line. RepositoryContentDescriptionParserConstants.java */
package org.texai.kb.persistence.parser;

public interface RepositoryContentDescriptionParserConstants {

  int EOF = 0;
  int LPAREN = 8;
  int RPAREN = 9;
  int CLASS_NAME = 10;
  int INDICES = 11;
  int DOT = 12;
  int DASH = 13;
  int INDEX_LITERAL = 14;
  int IDENTIFIER = 15;
  int LETTER = 16;
  int DIGIT = 17;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"(\"",
    "\")\"",
    "\"className:\"",
    "\"indices:\"",
    "\".\"",
    "\"-\"",
    "<INDEX_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
