/* Generated By:JavaCC: Do not edit this line. RuleParserConstants.java */
package org.texai.inference.ruleParser;

public interface RuleParserConstants {

  int EOF = 0;
  int LPAREN = 8;
  int RPAREN = 9;
  int LBRACE = 10;
  int RBRACE = 11;
  int LBRACKET = 12;
  int RBRACKET = 13;
  int SEMICOLON = 14;
  int COMMA = 15;
  int DOT = 16;
  int COLON = 17;
  int QUESTION = 18;
  int DASH = 19;
  int INTEGER_LITERAL = 20;
  int DECIMAL_LITERAL = 21;
  int HEX_LITERAL = 22;
  int OCTAL_LITERAL = 23;
  int FLOATING_POINT_LITERAL = 24;
  int EXPONENT = 25;
  int CHARACTER_LITERAL = 26;
  int STRING_LITERAL = 27;
  int IDENTIFIER = 28;
  int LETTER = 29;
  int DIGIT = 30;
  int VARIABLE = 31;
  int QNAME = 32;
  int DESCRIPTION = 33;
  int IF = 34;
  int THEN = 35;
  int CONTEXT = 36;
  int URI_GENERAL_DELIMITER = 37;
  int URI_SUB_DELIMITER = 38;
  int URI_RESERVED_CHAR = 39;
  int URI_UNRESERVED_CHAR = 40;
  int LANGLE = 41;
  int RANGLE = 42;
  int URI = 43;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "\"?\"",
    "\"-\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<VARIABLE>",
    "<QNAME>",
    "\"description:\"",
    "\"if:\"",
    "\"then:\"",
    "\"context:\"",
    "<URI_GENERAL_DELIMITER>",
    "<URI_SUB_DELIMITER>",
    "<URI_RESERVED_CHAR>",
    "<URI_UNRESERVED_CHAR>",
    "\"<\"",
    "\">\"",
    "<URI>",
  };

}
